import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    welcome: 'Welcome',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    pin: 'PIN',
    phone: 'Phone Number',
    name: 'Name',
    logout: 'Logout',
    userType: 'I am a',
    user: 'User',
    provider: 'Service Provider',
    services: 'Services',
    bookings: 'Bookings',
    cart: 'Cart',
    profile: 'Profile',
    search: 'Search services...',
    district: 'District',
    category: 'Category',
    allDistricts: 'All Districts',
    allCategories: 'All Categories',
    viewDetails: 'View Details',
    addToCart: 'Add to Cart',
    book: 'Book Now',
    status: 'Status',
    pending: 'Pending',
    inProgress: 'In Progress',
    completed: 'Completed',
    paymentMethod: 'Payment Method',
    upi: 'UPI',
    cash: 'Cash',
    advanceUpi: 'Advance UPI',
    address: 'Address',
    addAddress: 'Add Address',
    streetName: 'Street Name',
    city: 'City',
    pincode: 'Pincode',
    landmark: 'Landmark (Optional)',
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    changePin: 'Change PIN',
    forgotPin: 'Forgot PIN?',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify OTP',
    resendOtp: 'Resend OTP',
    trackBooking: 'Track Booking',
    bookingId: 'Booking ID',
    myServices: 'My Services',
    addService: 'Add Service',
    editService: 'Edit Service',
    deleteService: 'Delete Service',
    servicePrice: 'Price',
    discount: 'Discount',
    description: 'Description',
    contactProvider: 'Contact Provider',
    findTrusted: 'Find Trusted Service Providers Across',
    connectWith: 'Connect with verified earth movers, packers, bore well services, and power tool rentals in your district.',
    getStarted: 'Get Started',
    browseServices: 'Browse Services',
    ourCategories: 'Our Service Categories',
    professionalServices: 'Professional services available in all 39 districts of TamilNadu',
    whyChoose: 'Why Choose ServiceHub TN?',
    districtCoverage: 'District-wide Coverage',
    servicesAvailable: 'Services available in all TamilNadu districts',
    verifiedProviders: 'Verified Providers',
    allProviders: 'All service providers are verified with ratings',
    transparentPricing: 'Transparent Pricing',
    comparePrices: 'Compare prices and discounts easily',
    readyToStart: 'Ready to Get Started?',
    joinThousands: 'Join thousands of satisfied customers across TamilNadu',
    registerNow: 'Register Now',
    showingResults: 'Showing results for',
    show: 'Show',
    servicesPerPage: 'services per page',
    showing: 'Showing',
    of: 'of',
    servicesText: 'services',
    previous: 'Previous',
    next: 'Next',
    selectDistrict: 'Select District',
    selectCategory: 'Select Category',
    price: 'Price',
    provider: 'Provider',
  },
  ta: {
    welcome: 'வரவேற்கிறோம்',
    login: 'உள்நுழைய',
    register: 'பதிவு செய்ய',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    pin: 'பின்',
    phone: 'தொலைபேசி எண்',
    name: 'பெயர்',
    logout: 'வெளியேறு',
    userType: 'நான் ஒரு',
    user: 'பயனர்',
    provider: 'சேவை வழங்குநர்',
    services: 'சேவைகள்',
    bookings: 'முன்பதிவுகள்',
    cart: 'கூடை',
    profile: 'சுயவிவரம்',
    search: 'சேவைகளைத் தேடுங்கள்...',
    district: 'மாவட்டம்',
    category: 'வகை',
    allDistricts: 'அனைத்து மாவட்டங்கள்',
    allCategories: 'அனைத்து வகைகள்',
    viewDetails: 'விவரங்களைக் காண்க',
    addToCart: 'கூடையில் சேர்க்கவும்',
    book: 'இப்போதே முன்பதிவு செய்க',
    status: 'நிலை',
    pending: 'நிலுவையில்',
    inProgress: 'செயல்பாட்டில்',
    completed: 'நிறைவு',
    paymentMethod: 'கட்டண முறை',
    upi: 'யூபிஐ',
    cash: 'பணம்',
    advanceUpi: 'முன்கூட்டியே யூபிஐ',
    address: 'முகவரி',
    addAddress: 'முகவரி சேர்க்கவும்',
    streetName: 'தெரு பெயர்',
    city: 'நகரம்',
    pincode: 'அஞ்சல் குறியீடு',
    landmark: 'அடையாளம் (விருப்பம்)',
    save: 'சேமிக்கவும்',
    cancel: 'ரத்துசெய்',
    submit: 'சமர்ப்பிக்கவும்',
    changePin: 'பின் மாற்றவும்',
    forgotPin: 'பின் மறந்துவிட்டதா?',
    sendOtp: 'ஓடிபி அனுப்பவும்',
    verifyOtp: 'ஓடிபி சரிபார்க்கவும்',
    resendOtp: 'ஓடிபி மீண்டும் அனுப்பவும்',
    trackBooking: 'முன்பதிவைக் கண்காணிக்கவும்',
    bookingId: 'முன்பதிவு ஐடி',
    myServices: 'எனது சேவைகள்',
    addService: 'சேவை சேர்க்கவும்',
    editService: 'சேவையைத் திருத்தவும்',
    deleteService: 'சேவையை நீக்கவும்',
    servicePrice: 'விலை',
    discount: 'தள்ளுபடி',
    description: 'விளக்கம்',
    contactProvider: 'வழங்குநரைத் தொடர்பு கொள்ளவும்',
    findTrusted: 'நம்பகமான சேவை வழங்குநர்களைக் கண்டறியுங்கள்',
    connectWith: 'உங்கள் மாவட்டத்தில் சரிபார்க்கப்பட்ட அகழ்வாரர்கள், பேக்கர்கள், துளை கிணறு சேவைகள் மற்றும் மின் கருவி வாடகைகளுடன் இணைக்கவும்.',
    getStarted: 'தொடங்குங்கள்',
    browseServices: 'சேவைகளை உலாவவும்',
    ourCategories: 'எங்கள் சேவை வகைகள்',
    professionalServices: 'தமிழ்நாட்டின் அனைத்து 39 மாவட்டங்களிலும் தொழில்முறை சேவைகள் கிடைக்கின்றன',
    whyChoose: 'ஏன் ServiceHub TN ஐ தேர்வு செய்ய வேண்டும்?',
    districtCoverage: 'மாவட்ட அளவிலான கவரேஜ்',
    servicesAvailable: 'தமிழ்நாட்டின் அனைத்து மாவட்டங்களிலும் சேவைகள் கிடைக்கின்றன',
    verifiedProviders: 'சரிபார்க்கப்பட்ட வழங்குநர்கள்',
    allProviders: 'அனைத்து சேவை வழங்குநர்களும் மதிப்பீடுகளுடன் சரிபார்க்கப்பட்டுள்ளனர்',
    transparentPricing: 'வெளிப்படையான விலை நிர்ணயம்',
    comparePrices: 'விலைகளையும் தள்ளுபடிகளையும் எளிதாக ஒப்பிடுங்கள்',
    readyToStart: 'தொடங்க தயாரா?',
    joinThousands: 'தமிழ்நாடு முழுவதும் ஆயிரக்கணக்கான திருப்தியான வாடிக்கையாளர்களுடன் சேருங்கள்',
    registerNow: 'இப்போதே பதிவு செய்யுங்கள்',
    showingResults: 'முடிவுகளைக் காட்டுகிறது',
    show: 'காட்டு',
    servicesPerPage: 'ஒரு பக்கத்திற்கு சேவைகள்',
    showing: 'காட்டுகிறது',
    of: 'இல்',
    servicesText: 'சேவைகள்',
    previous: 'முந்தைய',
    next: 'அடுத்தது',
    selectDistrict: 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
    selectCategory: 'வகையைத் தேர்ந்தெடுக்கவும்',
    price: 'விலை',
    provider: 'வழங்குநர்',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = (newLang) => {
    if (typeof newLang === 'string' && (newLang === 'en' || newLang === 'ta')) {
      setLanguage(newLang);
    } else {
      setLanguage((prev) => (prev === 'en' ? 'ta' : 'en'));
    }
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      <div className={language === 'ta' ? 'tamil-text' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
